name: mlops_group5_env  # Name of the conda environment

channels:
  - conda-forge  # Community channel with most up-to-date packages

dependencies:
  - python=3.10.17       # Stable and widely-used Python version for compatibility
  - pandas=2.2.3            # Core library for data loading (CSV, Excel) and manipulation
  - numpy=2.2.6             # Fundamental package for numerical computing
  - openpyxl=3.1.5          # Excel support for pandas (read/write .xlsx files)
  - pyyaml=6.0.2            # Read configuration from YAML files for flexibility
  - python-dotenv=1.1.0     # Load environment variables from a .env file (for secrets/config)
  - pytest=8.3.5            # Testing framework for robust, maintainable code
  - pytest-dotenv=0.5.2     # Load environment variables from .env files in pytest
  - scikit-learn=1.6.1      # Machine learning library for model training and evaluation
  - pip=25.1.1                # Allows pip-only packages to be installed below
  - hydra-core           # Core library for Hydra configuration management
  - omegaconf            # Configuration management library for structured configs
  - dvc                  # Data Version Control for managing ML datasets and models
  - dvc-s3               # DVC extension for S3 storage support (for dataset management)
  - awscli               # AWS Command Line Interface for interacting with AWS services

  - pip:
      - pytest-cov==6.1.1  # Test coverage reporting for code quality and completeness
      - black==25.1.0       # Code formatting to enforce style and readability
      - flake8==7.2.0      # Linting to check code for errors and best practices
      - mlflow-skinny==2.22.0  # Experiment tracking and model management
      - wandb==0.19.11         # Weights & Biases for experiment tracking and visualization
