name: evaluation
channels:
  - conda-forge

dependencies:
  - python=3.10
  - pandas
  - scikit-learn
  - matplotlib
  - hydra-core
  - omegaconf
  - python-dotenv
  - pyyaml
  - pip
  - pip:
      - wandb